%include "colon.inc"

colon "DoctorLivesey", DoctorLivesey
db "Очень хороший и веселый человек, характер АХАХАХАХ, не женат.", 0

colon "BillyBones", BillyBones
db "Он же капитан, обладатель карты острова сокровищ. Много пьет, всегда простужен, характер скверный, не женат.", 0

colon "SquireTrelawny", SquireTrelawny
db "Туп, жаден, прожорлив, ленив, труслив, надменен, характер отсутствует, не женат.", 0

colon "JimHawkins", JimHawkins
db "Это я увёл Испаньолу!", 0

colon "CapitanSmollet", CapitanSmollet
db "Мне не нравится эта экспедиция! Мне не нравятся эти матросы! И вообще... Что? Да! Нет, мне вообще ничего не нравится, сэр!", 0

colon "BlindPew", BlindPew
db "Старый пират, друг Флинта, жаден, ради денег готов на все, характер мерзкий, не женат.", 0

colon "BlackDog", BlackDog
db "Где карта, Билли? Нам нужна карта.", 0
