CREATE TABLE HUMAN
(
    HUMAN_ID    SERIAL PRIMARY KEY,
    NAME        VARCHAR(20) NOT NULL,
    AGE         SMALLINT NOT NULL
        CHECK(AGE >= 0)
);

CREATE TABLE BRANCH
(
    BRANCH_ID   SERIAL PRIMARY KEY,
    SIZE        INTEGER NOT NULL,
    WOOD_TYPE   VARCHAR(20) NOT NULL
        CHECK(SIZE >= 0)
);

CREATE TABLE FLOWER
(
    FLOWER_ID   SERIAL PRIMARY KEY,
    BRANCH_ID   INTEGER REFERENCES BRANCH ON DELETE CASCADE NOT NULL,
    FLOWER_NUM  INTEGER NOT NULL,
    BLOOMED     INTEGER NOT NULL,
    SIZE        INTEGER NOT NULL
        CHECK(SIZE >= 0 AND BLOOMED >= 0 AND BLOOMED <= 100)
);

CREATE TABLE SCENE
(
    SCENE_ID            SERIAL PRIMARY KEY,
    FRAMES_PER_SECOND   SMALLINT
        CHECK(FRAMES_PER_SECOND >= 0)
);

CREATE TABLE WATCH
(
    SCENE_ID   INTEGER REFERENCES SCENE ON DELETE CASCADE NOT NULL,
    HUMAN_ID   INTEGER REFERENCES HUMAN ON DELETE CASCADE NOT NULL
);

CREATE TABLE FRAME
(
    FRAME_ID            SERIAL PRIMARY KEY,
    SCENE_ID            INTEGER REFERENCES SCENE ON DELETE CASCADE NOT NULL,
    FLOWER_ID           INTEGER REFERENCES FLOWER ON DELETE CASCADE NOT NULL,
    COUNTER             INTEGER NOT NULL,
    SCREEN_RESOLUTION   INTEGER ARRAY[2] NOT NULL,
    COLOR_DEPTH         BIGINT NOT NULL
        CHECK(  SCREEN_RESOLUTION[0] >= 0 AND
                SCREEN_RESOLUTION[1] >= 0 AND
                COLOR_DEPTH >= 0)
);

INSERT INTO HUMAN (NAME, AGE)
VALUES ('ME', 3),
       ('NOT ME', 10);

INSERT INTO BRANCH (SIZE, WOOD_TYPE)
VALUES (10, 'Роза'),
       (20, 'Сирень');

INSERT INTO FLOWER (FLOWER_NUM, BRANCH_ID, BLOOMED, SIZE)
VALUES (1, 1, 0, 10),
       (1, 1, 20, 50),
       (1, 1, 50, 70),
       (1, 1, 90, 90),
       (1, 1, 100, 150),
       (2, 2, 20, 5),
       (2, 2, 50, 20);

INSERT INTO SCENE (FRAMES_PER_SECOND)
VALUES (24),
       (24),
       (24);

INSERT INTO WATCH (SCENE_ID, HUMAN_ID)
VALUES (1, 1),
       (2, 1),
       (3, 1),
       (2, 2);

INSERT INTO FRAME (SCENE_ID, FLOWER_ID, COUNTER, SCREEN_RESOLUTION, COLOR_DEPTH)
VALUES (1, 1, 0, '{1920, 1080}', 255),
       (1, 2, 1, '{1920, 1080}', 255),
       (1, 3, 2, '{1920, 1080}', 255),
       (1, 4, 3, '{1920, 1080}', 255),
       (1, 5, 4, '{1920, 1080}', 255),
       (1, 6, 5, '{1920, 1080}', 255),
       (1, 7, 6, '{1920, 1080}', 255),
       (2, 6, 0, '{1920, 1080}', 255),
       (2, 7, 1, '{1920, 1080}', 255),
       (2, 1, 2, '{1920, 1080}', 255),
       (2, 2, 3, '{1920, 1080}', 255),
       (2, 3, 4, '{1920, 1080}', 255),
       (2, 4, 5, '{1920, 1080}', 255),
       (2, 5, 6, '{1920, 1080}', 255),
       (2, 6, 7, '{1920, 1080}', 255),
       (2, 7, 8, '{1920, 1080}', 255);


SELECT SCENE_ID, MAX(BLOOMED) - MIN(BLOOMED) AS DIFF
FROM FRAME JOIN FLOWER F ON F.FLOWER_ID = FRAME.FLOWER_ID
GROUP BY FRAME.SCENE_ID, F.FLOWER_NUM;

SELECT *
FROM FRAME JOIN FLOWER F ON F.FLOWER_ID = FRAME.FLOWER_ID;

WITH DIFF_TAB AS (
    SELECT SCENE_ID, MAX(BLOOMED) - MIN(BLOOMED) AS DIFF
    FROM FRAME JOIN FLOWER F ON F.FLOWER_ID = FRAME.FLOWER_ID
    GROUP BY FRAME.SCENE_ID, F.FLOWER_NUM)
SELECT DISTINCT H.HUMAN_ID, H.NAME, H.AGE FROM
    DIFF_TAB JOIN WATCH W ON W.SCENE_ID = DIFF_TAB.SCENE_ID JOIN HUMAN H ON H.HUMAN_ID = W.HUMAN_ID
WHERE DIFF_TAB.DIFF = (SELECT MAX(DIFF_TAB.DIFF) FROM DIFF_TAB);
